### ISSUE TITLE
Relax constraints on Python version

### ISSUE THREAD

**Issue by kellino** [ReX-XAI/ReX#2]
At the moment, we have python==3.10 in the README. This was only the case because the handling of the toml library changed between versions 3.10 and 3.11. We should be able to relax this constraint.

**Comment by liz-is** [comment]
The CI runs fine on 3.10-3.12 (have not yet tested the new 3.13!). I've dropped the suggestion for 3.10 specifically in #7

**Comment by liz-is** [comment]
Closed by merge of #7!
