### ISSUE TITLE
run_with_data_on_device assumes imagenet

### ISSUE THREAD

**Issue by kellino** [ReX-XAI/ReX#9]
`run_with_data_on_device` in `onnx.py` has imagenet (3, 224, 224) hardcoded, with a hardcoded output tensor of [_, 1000]. This is obviously wrong.

**Comment by wittyicon29** [comment]
I’d like to make a PR to address the hardcoded input/output shapes in `run_with_data_on_device` in `onnx.py`. Could you please share any required guidelines for this issue?

**Comment by wittyicon29** [comment]
I’d like to make a PR to address the hardcoded input/output shapes in `run_with_data_on_device` in `onnx.py`.

**Comment by kellino** [comment]
Closed with https://github.com/ReX-XAI/ReX/commit/25f502fe8e105a65815c821ee7fbe5350447c121
